"""Bring what a live sleeve starts from up to date with the bar store.

    python -m backtest_core.zorro.live            (from a desktop session: it runs Zorro)

Run it after every update of the bar store, and always after a roll: the history and the state files are on the
adjusted price scale, which equals the traded contract's prices only since the last roll.

1. ``.t6`` history of every futures root, all years (a roll rescales every earlier bar).
2. ``Strategy/ZZFactors.h``, the roll table the scripts read.
3. The state files a ``-d LIVE`` start loads, exported to the end of the history: the dip-buy closes and the
   break touch speeds.

It does not touch ``History/AssetsLive.csv``: the contract named there must be the one the history now ends on,
and that is set by hand.
"""
from __future__ import annotations

from datetime import date, time, timedelta

from .. import bars
from . import export, paths, run

ROOTS = ("CL", "GC", "ES", "NQ")                       # the order of the blocks in ZZFactors.h
STATE_SCRIPTS = ("DipBuyNQ", "BreakGC", "BreakES")
DAILY_STATE = {"DipBuyNQ": "NQ"}                       # state files with one row per session
HEADER = """// ZZFactors.h -- generated by backtest_core.zorro.live; do not edit.
// Roll table per market: factor (adjusted / raw price) FV[j] applies from the bar closing at FT[j]
// (whole minutes since 1899-12-30, UTC) until the next entry. Minutes, not DATE values: a decimal
// DATE literal lost minutes of precision in lite-C and moved a GC roll.
"""


def write_factors() -> None:
    text = HEADER + "\n" + "\n".join(export.factor_block(r) for r in ROOTS)
    (paths.SCRIPTS_DIR / "ZZFactors.h").write_text(text, encoding="ascii", newline="\r\n")


def drop_open_session(script: str, root: str) -> None:
    """Remove the last close from a daily state file when the history stops inside that session.

    The export writes one close per bar, and the last bar is cut short when the bar store ends mid-session. A
    live start skips every session the file holds, so a half session there would hide the real close for good.
    """
    last = bars.intraday(root, "databento", "1m", ["start"])["start"].max()
    if time(16, 55) <= last.time() < time(18, 0):       # the session's last minutes are in: it is complete
        return
    open_session = (last + timedelta(hours=6)).strftime("%Y%m%d")
    f = paths.ZORRO_DIR / "Data" / f"{script}_state.csv"
    lines = f.read_text().splitlines()
    kept = [x for x in lines if not x.startswith(open_session + ",")]
    f.write_text("\n".join(kept) + "\n")
    print(f"{script}: dropped {len(lines) - len(kept)} close of the open session {open_session}", flush=True)


def refresh() -> None:
    for r in ROOTS:
        n = export.t6(r)
        last = bars.intraday(r, "databento", "1m", ["start"])["start"].max()
        print(f"{r}: {sum(n.values()):,} bars in {len(n)} year files, history ends {last} ET", flush=True)
    write_factors()
    run.deploy()
    today = int(date.today().strftime("%Y%m%d"))
    for s in STATE_SCRIPTS:
        run.run(s, 0, today, defines=["STATE_LATEST"], timeout=3600)
        print(f"{s}: state exported", flush=True)
    for script, root in DAILY_STATE.items():
        drop_open_session(script, root)
    for f in sorted((paths.ZORRO_DIR / "Data").glob("*_state.csv")) + sorted((paths.ZORRO_DIR / "Data").glob("*_touches.csv")):
        lines = f.read_text().splitlines()
        print(f"  {f.name}: {len(lines):,} rows, last {lines[-1]}", flush=True)


if __name__ == "__main__":
    refresh()
