// NoiseAreaFull.c -- copy of NoiseArea.c run to 2026-09 for the portfolio. QQQ "Noise Area" intraday momentum (Zarattini, Aziz & Barbon 2024).
// Port of Hephaestus/backtests/es_noise_area/engine_na.py::simulate, as traded on QQQ
// (backtests/qqq_noise_area). parity.py compares this script's signal log with the Python engine.
//
// Rules
//   sigma(m) = mean over the prior 14 full sessions of |close(m) / open(09:30) - 1|, per minute of the day
//   Upper    = max(today's open, prior close) * (1 + sigma)
//   Lower    = min(today's open, prior close) * (1 - sigma)
//   Checks at 10:00, 10:30 ... 15:30 on the close of the bar ending then; fills at the NEXT bar's open.
//   Flat: long above Upper, short below Lower. Long exits below max(Upper, VWAP); short exits above
//   min(Lower, VWAP); then the entry rule is applied again at the same check. Flat at the 16:00 close.
//   1x notional, cost $0.017 per share round trip (one tick + IBKR commission).
//
// Runs on the free Zorro (backtest only). The free version cannot read a .t6 file's extra fields, so:
//   - the dividend adjustment factor comes from NAFactors.h, a table generated by export_t6.py;
//   - VWAP comes from a second asset, QQQVW, whose price each minute IS QQQ's session VWAP (typical price x
//     volume, regular hours), computed by export_t6.py. Everything else -- bands, signals, trades -- is Zorro's.
// Live trading needs real volume (marketVol), which needs Zorro S.
// Data: History/QQQ_YYYY.t6 (raw prices), History/QQQVW_YYYY.t6. Asset list: History/AssetsNoiseArea.csv.

#include <default.c>       // needed first once a script has any #include of its own
#include "NAFactors.h"

#define LOOKBACK_SESSIONS 14
#define NBARS 390          // 1-minute bars, 09:30 -> 16:00 ET
#define DONE_IDX 385       // a session counts only if it has a bar starting 15:55 or later
#define NOTIONAL 100000
#define SIGNAL_LOG "Log/NoiseAreaFull_signals.csv"

var Ring[5460];            // NBARS * LOOKBACK_SESSIONS: [minute index * 14 + session column]
var Today[390];
int Committed, LastIdx, StartOk, CurDate, Pos, FI;
var DayOpen, DayFactor, LastClose, LastFactor, CprevRaw, CprevFactor;

// action: 1 long, -1 short, 0 exit on the stop, 9 flat at the close, 2 check with no action
void logSignal(int action, var P, var UB, var LB, var VWAP)
{
	file_append(SIGNAL_LOG, strf("%.8f,%i,%.4f,%.4f,%.4f,%.4f\n", wdate(0), action, P, UB, LB, VWAP));
}

// US Eastern time from UTC (DST rules from 2007): Zorro's own zone table is only documented to 2024.
int dowOle(var t) { return ((int)floor(t) + 6) % 7; }          // 0 = Sunday
var etFromUtc(var t)
{
	int y = ymd(t) / 10000;
	var mar1 = dmy(y * 10000 + 301);
	var nov1 = dmy(y * 10000 + 1101);
	var dstStart = mar1 + ((7 - dowOle(mar1)) % 7) + 7 + 7. / 24;   // second Sunday of March, 02:00 EST
	var dstEnd = nov1 + ((7 - dowOle(nov1)) % 7) + 6. / 24;         // first Sunday of November, 02:00 EDT
	if(t >= dstStart && t < dstEnd) return t - 4. / 24;
	return t - 5. / 24;
}

var factorNow()
{
	int m = (int)floor(wdate(0) * 1440 + 0.5);      // bar close in whole minutes since 1899-12-30
	while(FI + 1 < QQQ_NF && QQQ_FT[FI + 1] <= m) FI++;
	return QQQ_FV[FI];
}

function run()
{
	set(LOGFILE);
	BarPeriod = 1;
	BarMode = 0;               // every bar in the history: the default week end blocked Friday 16:00 close-outs
	Outlier = 1000;            // off: never let Zorro "repair" a real price move
	LookBack = 0;              // the 14-session warm-up is handled below, not by Zorro's series
	StartDate = 20110323;
	EndDate = 20260922;        // full history (NoiseArea.c keeps the in-sample window)
	Capital = NOTIONAL;
	assetList("AssetsNoiseArea");
	asset("QQQVW");            // VWAP carrier: read, never traded
	asset("QQQ");
	Spread = 0;                // the tick is inside the $0.017 commission, as in the Python engine
	Slippage = 0;
	Fill = 3;                  // market orders fill at the next bar's open

	int k;
	if(is(INITRUN)) {
		Committed = 0; LastIdx = -1; StartOk = 0; CurDate = 0; Pos = 0; FI = 0;
		CprevRaw = 0; CprevFactor = 1;
		for(k = 0; k < 5460; k++) Ring[k] = 0;
		file_delete(SIGNAL_LOG);
		file_append(SIGNAL_LOG, "ole_utc,action,price,upper,lower,vwap\n");
		return;                // the first run comes before any prices are loaded
	}

	var et = etFromUtc(wdate(0));                                        // bar CLOSE time, New York
	int minuteOfDay = (int)floor((et - floor(et)) * 1440 + 0.5);
	int idx = minuteOfDay - 570 - 1;                                     // 0 = bar starting 09:30
	if(idx < 0 || idx >= NBARS) return;
	int today = ymd(et);
	var factor = factorNow();

	asset("QQQVW");
	var VWAP = priceClose(0);
	asset("QQQ");

	// New session: commit yesterday to the lookback if it was a full session.
	if(today != CurDate) {
		if(CurDate != 0 && StartOk && LastIdx >= DONE_IDX) {
			var lastMove = abs(LastClose / DayOpen - 1);
			for(k = LastIdx + 1; k < NBARS; k++) Today[k] = lastMove;   // missing minutes carry the last close
			int col = Committed % LOOKBACK_SESSIONS;
			for(k = 0; k < NBARS; k++) Ring[k * LOOKBACK_SESSIONS + col] = Today[k];
			Committed++;
			CprevRaw = LastClose;
			CprevFactor = LastFactor;
		}
		CurDate = today;
		DayOpen = priceOpen(0);
		DayFactor = factor;
		StartOk = (idx == 0);
		LastIdx = -1;
		Pos = 0;
		for(k = 0; k < NBARS; k++) Today[k] = 0;
	}

	// Record this minute's move (carrying the last close over any missing minutes).
	if(LastIdx >= 0 && idx > LastIdx + 1) {
		var fillMove = abs(LastClose / DayOpen - 1);
		for(k = LastIdx + 1; k < idx; k++) Today[k] = fillMove;
	}
	var P = priceClose(0);
	Today[idx] = abs(P / DayOpen - 1);
	LastIdx = idx;
	LastClose = P;
	LastFactor = factor;

	if(Committed < LOOKBACK_SESSIONS || CprevRaw <= 0) return;

	var acc = 0;
	for(k = 0; k < LOOKBACK_SESSIONS; k++) acc += Ring[idx * LOOKBACK_SESSIONS + k];
	var sigma = acc / LOOKBACK_SESSIONS;
	var cprev = CprevRaw * CprevFactor / DayFactor;          // yesterday's close on today's price scale
	var UB = max(DayOpen, cprev) * (1 + sigma);
	var LB = min(DayOpen, cprev) * (1 - sigma);

	// Checks: bars closing 10:00, 10:30 ... 15:30.
	if(idx >= 29 && idx <= 359 && (idx + 1) % 30 == 0) {
		int acted = 0;
		if(Pos == 1 && P < max(UB, VWAP)) {
			exitLong(); Pos = 0; acted = 1; logSignal(0, P, UB, LB, VWAP);
		} else if(Pos == -1 && P > min(LB, VWAP)) {
			exitShort(); Pos = 0; acted = 1; logSignal(0, P, UB, LB, VWAP);
		}
		if(Pos == 0) {
			if(P > UB) {
				Lots = (int)(NOTIONAL / P);
				enterLong(); Pos = 1; acted = 1; logSignal(1, P, UB, LB, VWAP);
			} else if(P < LB) {
				Lots = (int)(NOTIONAL / P);
				enterShort(); Pos = -1; acted = 1; logSignal(-1, P, UB, LB, VWAP);
			}
		}
		if(!acted) logSignal(2, P, UB, LB, VWAP);
	}

	// Flat at the 16:00 close, filled at this bar's close rather than tomorrow's open.
	if(idx == NBARS - 1 && Pos != 0) {
		Fill = 1;
		if(Pos == 1) exitLong(); else exitShort();
		Pos = 0;
		logSignal(9, P, UB, LB, VWAP);
	}
}
